name:                rosoku
version:             0.1.0.0
github:              "dansvidania/rosoku"
license:             BSD3
author:              "Danilo Amoroso"
maintainer:          "dan.w.amoroso@gmail.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dansvidania/rosoku#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck >= 2

library:
  source-dirs: src

executables:
  rosoku-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rosoku

tests:
  rosoku-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rosoku
    - QuickCheck 
